BBN-Q/Qlab

- experiments/LPN/digitizeShots.m
- experiments/RUS/fast_tomo_1q.m
- experiments/RUS/fast_tomo_1q_2m.m
- experiments/RUS/fast_tomo_2q.m
- experiments/SLOW/coupler_power_sweep.m
- experiments/SLOW/pump_bias_sweep.m
- experiments/SLOW/pump_coupler_sweep.m
Miscellanous scripts for various experiments, just reorganized in their own folders.
> Feature exp scripts

- common/+deviceDrivers/Agilent53131A.m
- common/+deviceDrivers/AgilentN9020A.m
- common/+deviceDrivers/Keithley195A.m
- common/+deviceDrivers/Keithley2400.m
- common/+deviceDrivers/SR7124.m
- common/+deviceDrivers/SRS865.m
Updated driver for:
-Agilent 53131A (Counter)
New drivers for:
-Keithley 195A
-Agilent N9020A (Spectrum Analyzer)
- SRS 865 (Lock-In Amplifier)
> Updated and New Device Drivers for graphene experiments

- common/+deviceDrivers/Agilent33220A.m
- common/+deviceDrivers/AgilentE3631A.m
- common/+deviceDrivers/HP8153A.m
- common/+deviceDrivers/Keithley2400.m
*New drivers for AgilentE3631A Triple Power Supply and HP8153A Lightwave
Meter
*Update Keithley 2400 driver to include filtering properties (averaging
mode, number of counts per average, and NPLC)
> New and Updated Instrument Drivers

- common/+MeasFilters/DigitalDemod.m
> Degtorad requires Mapping toolbox

- common/+MeasFilters/SingleShot.m
- common/@SingleShotFidelity/SingleShotFidelity.m
To optionally cancel DC offsets in the signal
--DR
> Kernel with zero mean

- experiments/muWaveDetection/src/@MixerOptimizer/MixerOptimizer.m
Same as for Ramsey calibration.
I find more useful to update a master settings file rather than the instruments., when  interspersing ExpScripter with calibratePulses/optimize_mixer. 
--DR
> Update CurScripterFile in MixerOptimizer

- analysis/cQED_dataAnalysis/fitramsey2D.m
freqs was used for two different things inside the loop.
> unfortunate variable colision

- common/@PulseCalibration/APE.py
- common/@PulseCalibration/PhaseEstimationSequence.py
- common/@PulseCalibration/Pi2Cal.py
- common/@PulseCalibration/PiCal.py
- common/@PulseCalibration/RabiAmp.py
- common/@PulseCalibration/RamseySequence.py
- common/@PulseCalibration/SPAM.py
- common/@SingleShotFidelity/SingleShotSequence.py
- experiments/LPN/LPNSequence.py
- experiments/RB/RB2QSequence.py
- experiments/Twirl/TwirlSequence.py
- experiments/muWaveDetection/CRCal.py
I may be missing a bunch more
--DR
> Remove call to obsolete startup.py

- analysis/cQED_dataAnalysis/QPT_SDP.m
- analysis/cQED_dataAnalysis/analyzeProcessTomo.m
Adapt the older function QPT_LSQ (not used) for compatibility into
QPT_SDP and analyzeProcessTomo
--DR
> Optional rescaling of data by variance

- analysis/cQED_dataAnalysis/CR_tomography.m
- analysis/cQED_dataAnalysis/calculateResidue_CR.m
- analysis/cQED_dataAnalysis/fit_rabiCR.m
Functions for CR-hamiltonian tomography, IBM method.
--DR
> Functions for CR hamiltonian tomography

- analysis/cQED_dataAnalysis/analyzeCalCR.m
- common/util/updateLengthPhase.m
- common/util/updateLengthPhaseParams.py
- experiments/muWaveDetection/CRCal.py
- experiments/muWaveDetection/calibrateCR.m
Reorganized CR cal. and added option of fine tuning the amplitude
--DR
> Add calibration step for fine tuning of CR amp.

- common/@PulseCalibration/PulseCalibrationDo.m
- experiments/muWaveDetection/calibratePulses.m
1) Set a condition on the maximum frequency change that can be set by a Ramsey calibration 
2) Update master settings file with calibrated offsets
--DR
> Fix qubit cal

- common/@PulseCalibration/PhaseEstimation.m
I think this should unwrap the phase as above, so that pi and -pi are
the same angle
> Fix uncertainty estimate sigma

- experiments/muWaveDetection/src/@MixerOptimizer/MixerOptimizer.m
- experiments/muWaveDetection/src/@MixerOptimizer/optimize_mixer_offsets_bySweep.m
- experiments/muWaveDetection/src/@MixerOptimizer/setInstrument.m
For mixer calibration with on-board modulation
> Feature aps2 firmware v4

- experiments/T1T2/RamseySequence.py
- experiments/T1T2/T1Sequence.py
- experiments/T1T2/T1T2series.m
Support multiple acquisition cards and APS units (similar to pulse
calibration)
> Simple script to loop T1-T2 on multiple qubits

- analysis/cQED_dataAnalysis/analyzeProcessTomo.m
- analysis/cQED_dataAnalysis/tomo_gate_set.m
For now, implemented tetrahedral axes (4 prep. x 4 meas.)
> Allow different state/prep. tomography pulses

- analysis/cQED_dataAnalysis/fitramsey.m
- analysis/cQED_dataAnalysis/fitt1.m
Minor changes to fit functions
> Minor changes to fit functions

- common/util/updateAmpPhase.py
- common/util/updateLengthPhaseParams.py
- common/util/updateQubitPulseParams.py
Compatibility with https://github.com/BBN-Q/PyQLab/pull/115
> Fix path for channelLib

- common/@PulseCalibration/APEChannelSequence.m
- common/@PulseCalibration/PhaseEstimationSequence.m
- common/@PulseCalibration/PhaseEstimationSequence2q.m
- common/@PulseCalibration/Pi2CalChannelSequence.m
- common/@PulseCalibration/PulseCalibration.m
- common/@PulseCalibration/PulseCalibrationDo.m
- common/@PulseCalibration/RabiAmp.py
- common/@PulseCalibration/RamseyChannelSequence.m
- common/@PulseCalibration/SPAMChannelSequence.m
- common/@PulseCalibration/loadSequence.m
- common/@PulseCalibration/measure_rotation_angle.m
- common/@PulseCalibration/pi2ObjectiveFunction.m
- common/@PulseCalibration/piObjectiveFunction.m
- common/@PulseCalibration/rabiAmpChannelSequence.m
This branch only commits to it half way, since we still return `segmentPoints` from each sequence, rather than reading it from the meta info file.
> Use meta info in `PulseCalibration`

- common/+deviceDrivers/YokoGS200.m
Fix units and try to better approximate the set rate
> Fix some timing and definitions

- analysis/cQED_dataAnalysis/fit_two_freq.m
- analysis/cQED_dataAnalysis/fitramsey.m
- analysis/cQED_dataAnalysis/fitt1.m
Fit functions assume that the axis is in ns. This is a quick fix for fitting the active plot, adjusting the unit based on the axis label
> Read time units from figure axis

- analysis/cQED_dataAnalysis/analyzeCalCR.m
- common/ExpScripter2.m
- experiments/T1T2/T1T2series.m
- experiments/muWaveDetection/calibrateCR.m
Sweep settings for any list of points
> Set sweep points

- common/util/update_wf_lib.py
Use https://github.com/BBN-Q/QGL/pull/76 to update the full pulse library
> In-place-update of all AC pulses

- analysis/Resonator_fitting/fit_biased_lorentzian.m
- analysis/Resonator_fitting/fit_resonance_circle.m
Add fit functions for biased Lorentzian, and hanger resonator in complex plane that compensates for phase delay and scaling/rotation. 
My first PR to Qlab, so do let me know about any style issues...
-GJR
> Fancy fit functions for resonators.

- analysis/Resonator_fitting/fit_biased_lorentzian.m
Fixed missing factor of 2 in definition of Lorentzian FWHM when plotting 2D data.
> Correct definition of FWHM in 2D plotting.

- common/+sweeps/Repeat.m
This is sometimes useful for GST experiements.  Any interest in adding this to develop?
> Added optional delay between repeats.  -MW

- common/@ExpManager/ExpManager.m
Forgot to push this months ago
-- BRJ and DR
> Wait for all scopes to finish acquisition

- common/+deviceDrivers/Agilent33220A.m
- common/+deviceDrivers/SRS865.m
ouput ON/OFF
sync ON/OFF
Option to set frequency
Option to set rampSymmetry
fixed typo on SRS865
-EDW
> Added Functionality for Agilent33220
